version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - ipfs-proxy-db:/var/lib/postgresql/data

  # ipfs-proxy:
  #   build:
  #     context: .
  #   environment:
  #     DB_NAME: postgres
  #     DB_USERNAME: postgres
  #     DB_PASSWORD: postgres
  #     DB_HOST: postgres
  #     DB_PORT: 5432
  #   depends_on:
  #     - postgres
  #   ports:
  #     - '8080:8080'

volumes:
  ipfs-proxy-db: